### ISSUE TITLE
X18

### ISSUE THREAD

**Issue by tlindner** [hoglet67/6809Decoder#4]
This:
`C' = 0 where Bn is the byte a PC + 1 (the next opcode)`
I think should be:
`C' = 0`
`Where Bn is the byte at PC + 1 (the next opcode)`

**Comment by hoglet67** [comment]
Fixed

**Comment by dfffffff** [comment]
You should give me the credit for this opcode, [https://gitlab.com/dfffffff/6809_undoc/-/blob/a166a3c6c0f09227aeea8327bd30fbf7caffc21d/6809_undocumented_behavior.pdf](url)
page 4.
Following our discussion on facebook

**Comment by hoglet67** [comment]
Very happy to do this David.

I'll also add your document to the references section if that;s alright with you,

How would you like to be referred to?

**Comment by hoglet67** [comment]
I've made that change now David.
