### ISSUE TITLE
XDEC

### ISSUE THREAD

**Issue by tlindner** [hoglet67/6809Decoder#6]
Peter Philips prompted me to further test the XDEC instructions. Based on experiments on a real 6809, I have convinced myself the overflow flag (V) is set just like the DEC instruction.
It is not left unchanged as your documentation suggests.

**Comment by hoglet67** [comment]
The implementation of DECX in the 6809Decoder (dev branch) does indeed modify N/Z/V in the same way that DEC instruction, so this is a documentation bug. I've just corrected that.

But XDEC does modify C, whereas DEC leaves it unchanged, do you agree?

Here's that code, which I have a high degree of confidence in
https://github.com/hoglet67/6809Decoder/blob/dev/src/em_6809.c#L2548

**Comment by tlindner** [comment]
I agree.

**Comment by hoglet67** [comment]
Thanks, I'll close this then.

Please do raise further issues if you spot any more errors.
